# Generated by Django 2.1.1 on 2018-11-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181024_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='desc',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
