# Generated by Django 2.1.1 on 2018-11-07 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181107_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
