# Generated by Django 2.1.1 on 2018-10-26 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='staff/img/default.jpg', upload_to='staff/img')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=13)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary')], max_length=2)),
                ('civil_status', models.CharField(choices=[('SG', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('SE', 'Separated'), ('W', 'Widowed')], max_length=9)),
                ('position', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('appointment_file', models.FileField(blank=True, null=True, upload_to='staff/appointment')),
                ('pds_file', models.FileField(blank=True, null=True, upload_to='staff/pds')),
                ('prc_license_file', models.FileField(blank=True, null=True, upload_to='staff/prc_license')),
                ('saln_file', models.FileField(blank=True, null=True, upload_to='staff/saln_file')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
