# Generated by Django 2.1.1 on 2018-10-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=1)),
                ('section_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='advisory_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Section'),
        ),
    ]
