# Generated by Django 2.1.1 on 2018-10-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20181029_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='grade_level',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade_level', 'section_name')},
        ),
    ]
