# Generated by Django 2.1.1 on 2018-10-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20181029_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('lrn', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='acad_year',
            field=models.CharField(default='2018 - 2019', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='sections',
            field=models.ManyToManyField(to='administrator.Section'),
        ),
    ]
