# Generated by Django 2.1.1 on 2018-10-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20181031_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='gender',
            new_name='sex',
        ),
    ]
