# Generated by Django 2.1.1 on 2018-11-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20181031_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='acad_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sections',
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='administrator.Section'),
            preserve_default=False,
        ),
    ]
