# Generated by Django 2.1.1 on 2018-11-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20181105_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='pds_file',
            field=models.FileField(blank=True, null=True, upload_to='staff/pds', verbose_name='Personal Data Sheet'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='prc_license_file',
            field=models.FileField(blank=True, null=True, upload_to='staff/prc_license', verbose_name='PRC License Copy'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='saln_file',
            field=models.FileField(blank=True, null=True, upload_to='staff/saln_file', verbose_name='SALN Form'),
        ),
    ]
