# Generated by Django 2.1.1 on 2018-11-07 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0010_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Post',
        ),
    ]
