# Generated by Django 2.1.1 on 2018-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_auto_20181107_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade_level', 'name')},
        ),
    ]
