# Generated by Django 2.1.1 on 2018-11-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_auto_20181109_0500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Section',
        ),
    ]

    atomic = False
