# Generated by Django 2.1.1 on 2018-11-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_auto_20181109_0502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Class',
        ),
    ]

    atomic = False
