# Generated by Django 2.1.1 on 2018-11-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='remarks',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
