# Generated by Django 2.1.1 on 2018-11-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_auto_20181110_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.CharField(default='09266789842', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='Imelda Alincastre', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.TextField(default='San Juan, Malolos, Bulacan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.CharField(default=2, max_length=70),
            preserve_default=False,
        ),
    ]
