# Generated by Django 2.1.1 on 2018-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_auto_20181110_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='school_id',
            field=models.CharField(default='15-170338', help_text='Please follow the following format: 12-345678', max_length=9),
            preserve_default=False,
        ),
    ]
