# Generated by Django 2.1.1 on 2018-11-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_staff_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='school_id',
            field=models.CharField(help_text='Please follow the following format: 12-345678', max_length=9, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
