# Generated by Django 2.1.1 on 2018-11-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_auto_20181111_0128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Section',
        ),
    ]

    atomic = False
