# Generated by Django 2.1.1 on 2018-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_auto_20181111_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lrn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Learner Reference Number'),
        ),
    ]
