# Generated by Django 2.1.1 on 2018-11-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Term'),
            preserve_default=False,
        ),
    ]
