# Generated by Django 2.1.1 on 2018-11-16 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_auto_20181116_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'get_latest_by': '-start_date'},
        ),
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
