# Generated by Django 2.1.1 on 2018-11-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_auto_20181116_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade_level', 'name', 'term')},
        ),
    ]
